name: "test_all_models"
device: "cpu"
confidence_threshold: 0.5
iou_threshold: 0.2

# List of models to execute in order
models:
  - name: "vehicle"
    model_name: "yolo11_vehicle_seg"
    checkpoint: "runs/vehicle_seg_y11/best.pt"
    confidence_threshold: 0.079
  # - name: "angle"
  #   checkpoint: "runs/angle_resnet50_v3/checkpoints/best.pth"  # Update with actual path
  - name: "parts"
    model_name: "yolo11_seg"
    checkpoint: "runs/yolo11_t2/best.pt" # Update with actual path
    confidence_threshold: 0.3

  - name: "damage"
    model_name: "yolo11_seg"
    checkpoint: "runs/cardd_y11m/trained.pt" # Update with actual path
    confidence_threshold: 0.3

# Post-processing modules to run after all models
post_processors:
  - name: "damage_to_parts_orchestrator"
