_base_: ../base.yaml

experiment_name: yolo11_parts_seg_v1

model:
  name: yolo11_seg
  stage: parts
  weights: yolo11n-seg.pt

data:
  yaml_path: data/kaggle/data.yaml
  image_size: 640

training:
  epochs: 50
  patience: 5
  batch_size: 16
  optimizer:
    lr: 0.01

output:
  runs_dir: runs/parts_yolo11
