_base_: ../base.yaml

experiment_name: yolo11_damage_seg_v1

model:
  name: yolo11_seg
  stage: damage
  # variant: YOLO11m-seg
  weights: yolo11s-seg.pt

data:
  yaml_path: data/car_DD_damage_yolo/data.yaml
  image_size: 1024
  class_names: ['dent', 'scratch', 'crack', 'glass shatter', 'lamp broken', 'tire flat']

training:
  epochs: 50
  batch_size: 8
  optimizer:
    lr: 0.005
  # yolo_kwargs:
  #   optimizer: SGD
  #   momentum: 0.9
  #   weight_decay: 0.0005
  #   patience: 5
  #   cos_lr: true
  #   mosaic: 1.0

output:
  runs_dir: runs/damage_yolo11
